# Definir onde estão os códigos
sonar.sources=backend,frontend

# Ignorar prototipagem
sonar.exclusions=Prototipagem/**,**/seed_db/**

# Opcional: ignorar HTML se quiser
# sonar.exclusions=Prototipagem/**,**/seed_db/**,**/*.html
