# Identificação obrigatória
sonar.projectKey=wellingtonspdev_Sistema-Gerenciamento-Financeiro
sonar.organization=wellingtonspdev

# Código fonte
sonar.sources=backend,frontend
sonar.exclusions=Prototipagem/**,**/seed_db/**

# Coverage (MUUUITO importante)
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info

# Encoding
sonar.sourceEncoding=UTF-8  