sonar.sources=beckend,frontend
sonar.exclusions=Prototipagem/**,**/seed_db/**,**/node_modules/**,**/dist/**,**/build/**
sonar.javascript.lcov.reportPaths=beckend/coverage/lcov.info,frontend/coverage/lcov.info
sonar.sourceEncoding=UTF-8